-- 数据迁移脚本自动生成
-- 生成时间：2026-07-13T00:32:48.259Z
-- 源目录：src/content/*.md
-- 目标表：moments（D1 数据库 moments-db）
-- 说明：将 Markdown 内容迁移到 D1 moments 表

-- D1 不支持 BEGIN/COMMIT 事务语句，直接执行 INSERT

INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2023-10-17-first', '', 'text', '觉得自己像个神经一样，一会想通了，一会又想不通，不知道自己为什么会变成了这样，心里很难受，却还没法跟人说。', '<p>觉得自己像个神经一样，一会想通了，一会又想不通，不知道自己为什么会变成了这样，心里很难受，却还没法跟人说。</p>', '', '2023-10-17', '', 0, '[]', '', '', '', '', '', '', 1697500800000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2023-10-28-first', '', 'images', '', '', '', '2023-10-28', '', 0, '["https://images.izhch.com/2023/10/HUuYhBEta6vbop1.webp","https://images.izhch.com/2023/10/2RrnkeK6jqAzBbZ.webp"]', '', '', '', '', '', '', 1698451200000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2023-11-02-first', '', 'text', '其实我该一言不发', '<p>其实我该一言不发</p>', '', '2023-11-02', '', 0, '[]', '', '', '', '', '', '', 1698883200000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2023-11-11-first', '', 'text', '又把我删了，也不知道是第几次了，就这样吧。', '<p>又把我删了，也不知道是第几次了，就这样吧。</p>', '', '2023-11-11', '', 0, '[]', '', '', '', '', '', '', 1699660800000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2023-11-20-first', '', 'text', '想要进入你的生活，这种行为，确实打扰。', '<p>想要进入你的生活，这种行为，确实打扰。</p>', '', '2023-11-20', '', 0, '[]', '', '', '', '', '', '', 1700438400000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2023-12-03-first', '', 'images', '', '', '', '2023-12-03', '', 0, '["https://images.izhch.com/2023/12/RjZU4PB3oeJOCNi.webp"]', '', '', '', '', '', '', 1701561600000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2023-12-04-first', '', 'images', '被日出治愈一整天', '<p>被日出治愈一整天</p>', '', '2023-12-04', '', 0, '["https://images.izhch.com/2023/12/K9c2YxQRZLpOlk7.webp"]', '', '', '', '', '', '', 1701648000000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-01-10-first', '', 'text', '我并非无法保持安静，只不过有你相伴时，我的心思不再飘向别处。', '<p>我并非无法保持安静，只不过有你相伴时，我的心思不再飘向别处。</p>', '', '2024-01-10', '', 0, '[]', '', '', '', '', '', '', 1704844800000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-02-03-first', '', 'text', '第二次淋雨了，这次一定要买个伞。', '<p>第二次淋雨了，这次一定要买个伞。</p>', '', '2024-02-03', '', 0, '[]', '', '', '', '', '', '', 1706918400000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-02-10-first', '', 'text', '喜欢又怎么样了，喜欢都是短暂的。', '<p>喜欢又怎么样了，喜欢都是短暂的。</p>', '', '2024-02-10', '', 0, '[]', '', '', '', '', '', '', 1707523200000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-02-13-first', '', 'images', '这会是最后一次一起看电影吗？', '<p>这会是最后一次一起看电影吗？</p>', '', '2024-02-13', '', 0, '["https://images.izhch.com/2024/02/P9lm7xpzwET2DvX.webp"]', '', '', '', '', '', '', 1707782400000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-02-19-first', '', 'text', '你把窗户一关，全然不管外边发生了什么。你的夏天是结束了，那窗外面的云呢？', '<p>你把窗户一关，全然不管外边发生了什么。你的夏天是结束了，那窗外面的云呢？</p>', '', '2024-02-19', '', 0, '[]', '', '', '', '', '', '', 1708300800000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-03-02-first', '', 'text', '你情我愿，愿赌服输。', '<p>你情我愿，愿赌服输。</p>', '', '2024-03-02', '', 0, '[]', '', '', '', '', '', '', 1709337600000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-03-19-first', '', 'text', '在那个不经意的瞬间，我想起了和你共度的那些日子，那是一段充满欢笑与眼泪的时光。

那些日子里，你给予我的温暖如同阳光一般照亮我的世界，使我忘却了所有的忧伤与痛苦。

而现在，在你的缺席中，即使眼泪无声地滑落，心中的思念也如同秋天的落叶一般，默默地堆积。

然而，就在这一刻，让轻柔的风吹干了我的眼泪，我仿佛能感受到你的呼吸，听见你轻声的安慰。

这风，温柔地拥抱着我，像极了你当初给予的爱与关怀。

因此，即使泪水已干，你在我心中的位置，却永远湿润，永远温暖。', '<p>在那个不经意的瞬间，我想起了和你共度的那些日子，那是一段充满欢笑与眼泪的时光。</p>
<p>那些日子里，你给予我的温暖如同阳光一般照亮我的世界，使我忘却了所有的忧伤与痛苦。</p>
<p>而现在，在你的缺席中，即使眼泪无声地滑落，心中的思念也如同秋天的落叶一般，默默地堆积。</p>
<p>然而，就在这一刻，让轻柔的风吹干了我的眼泪，我仿佛能感受到你的呼吸，听见你轻声的安慰。</p>
<p>这风，温柔地拥抱着我，像极了你当初给予的爱与关怀。</p>
<p>因此，即使泪水已干，你在我心中的位置，却永远湿润，永远温暖。</p>', '', '2024-03-19', '', 0, '[]', '', '', '', '', '', '', 1710806400000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-03-22-first', '', 'images', '即使我们再也不能见面，也可以在看不到彼此的地方一起跳同一支舞。', '<p>即使我们再也不能见面，也可以在看不到彼此的地方一起跳同一支舞。</p>', '', '2024-03-22', '', 0, '["https://images.izhch.com/2024/03/yGZ24g9KjMoAneE.webp","https://images.izhch.com/2024/03/T3CP4ZwrX9KNDab.webp","https://images.izhch.com/2024/03/KUFWc7VRGfobsQx.webp","https://images.izhch.com/2024/03/Q6VwDSJN85ZbotR.webp"]', '', '', '', '', '', '', 1711065600000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-03-24-first', '', 'images', '一首歌的时间，我们的距离便拉得如此遥远。', '<p>一首歌的时间，我们的距离便拉得如此遥远。</p>', '', '2024-03-24', '', 0, '["https://images.izhch.com/2024/03/NkM63bEzvHRgeh7.webp"]', '', '', '', '', '', '', 1711238400000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-04-22-first', '', 'images', '', '', '', '2024-04-22', '', 0, '["https://images.izhch.com/2024/04/HoWJK4lZhLkSsyI.webp","https://images.izhch.com/2024/04/xvnHRFCdp98c1bM.webp","https://images.izhch.com/2024/04/xHt7JTXnePMiAVr.webp","https://images.izhch.com/2024/04/UonTVfZeLP1NBmI.webp","https://images.izhch.com/2024/04/QslZhmLjYa2dM9i.webp","https://images.izhch.com/2024/04/3unVLJdAY4k2zUW.webp"]', '', '', '', '', '', '', 1713744000000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-05-12-first', '', 'text', '只不过是恢复原状罢了，我本来就是一无所有的。', '<p>只不过是恢复原状罢了，我本来就是一无所有的。</p>', '', '2024-05-12', '', 0, '[]', '', '', '', '', '', '', 1715472000000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-07-31-first', '', 'images', '我以为很快就能见面，所以那天没有好好告别。', '<p>我以为很快就能见面，所以那天没有好好告别。</p>', '', '2024-07-31', '', 0, '["https://images.izhch.com/2024/07/LbRg4iyC3DSjr1k.webp"]', '', '', '', '', '', '', 1722384000000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-08-15-video-demo', '', 'video', '', '', '厦门市 · 鼓浪屿', '2026-06-15', '', 0, '[]', '', '', '', '', 'https://www.w3schools.com/html/mov_bbb.mp4', '0:10', 1781481600000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-09-09-first', '', 'images', '☁️', '<p>☁️</p>', '', '2024-09-09', '', 0, '["https://images.izhch.com/2024/09/JQEZ5z1p6YH7ibt.webp"]', '', '', '', '', '', '', 1725840000000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-09-14-first', '', 'images', '', '', '温州市 · 雁荡山', '2024-09-14', '', 0, '["https://images.izhch.com/2024/09/ba4uHdYpq17DFiv.webp","https://images.izhch.com/2024/09/QxpshKOTYH5nJB2.webp","https://images.izhch.com/2024/09/vUZMSBR8DTtNAxr.webp","https://images.izhch.com/2024/09/kTpiLmbHQ9R5uy8.webp","https://images.izhch.com/2024/09/eBXJgU2OsCZA63S.webp","https://images.izhch.com/2024/09/a4fSxNCnbRFgt5D.webp","https://images.izhch.com/2024/09/Skus9dIqOP7iTJr.webp","https://images.izhch.com/2024/09/3op6Y7sdDg8fC2J.webp","https://images.izhch.com/2024/09/3hCqg4EDYGBH7T5.webp"]', '', '', '', '', '', '', 1726272000000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-09-27-first', '', 'text', '“奇怪，怎么秋天了还有你这个春竹”', '<p>“奇怪，怎么秋天了还有你这个春竹”</p>', '', '2024-09-27', '', 0, '[]', '', '', '', '', '', '', 1727395200000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-09-30-first', '', 'images', '就这？一百多？', '<p>就这？一百多？</p>', '', '2024-09-30', '', 0, '["https://images.izhch.com/2024/09/9hE1gG354CNsBO2.webp"]', '', '', '', '', '', '', 1727654400000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-10-11-first', '', 'images', '', '', '', '2024-10-11', '', 0, '["https://images.izhch.com/2024/10/xsKcXR6EbD4Ne9a.webp","https://images.izhch.com/2024/10/PpiyFEDeM3Ss1R8.webp","https://images.izhch.com/2024/10/RW4yArhIkPYLZSd.webp","https://images.izhch.com/2024/10/DqVmwWceskY3Obo.webp","https://images.izhch.com/2024/10/zf2oM976HeAilkn.webp","https://images.izhch.com/2024/10/de1rlYByvVwmPbx.webp","https://images.izhch.com/2024/10/8KHXYGcVJBiozjA.webp","https://images.izhch.com/2024/10/EXTVWGn7yeQIkvM.webp","https://images.izhch.com/2024/10/LT2YQN6sjKPrRIH.webp"]', '', '', '', '', '', '', 1728604800000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-10-17-first', '', 'images', '', '', '泉州市 · 万达广场(泉州安溪店)', '2024-10-17', '', 0, '["https://images.izhch.com/2024/10/SehgjBby8RiAxCo.webp","https://images.izhch.com/2024/10/eOS6i9VxU2roQMt.webp"]', '', '', '', '', '', '', 1729123200000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-10-18-first', '', 'images', '', '', '莆田市 · 湄洲岛', '2024-10-18', '', 0, '["https://images.izhch.com/2024/10/w1jDrnNxgJ3iOab.webp","https://images.izhch.com/2024/10/rwbnxkT6MtONLE2.webp","https://images.izhch.com/2024/10/iu9S1tzB3bZUI62.webp","https://images.izhch.com/2024/10/twRAbo2O6FeaUkV.webp","https://images.izhch.com/2024/10/kZSL7xThi2bBgtJ.webp","https://images.izhch.com/2024/10/QHDMSGNYR3kvbXa.webp","https://images.izhch.com/2024/10/1XwpFMK4Pmnj7s8.webp","https://images.izhch.com/2024/10/VlQNjULKbquOTov.webp","https://images.izhch.com/2024/10/mEUM16kpKioCdv9.webp"]', '', '', '', '', '', '', 1729209600000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2024-11-28-first', '', 'text', '梦里超级想你', '<p>梦里超级想你</p>', '', '2024-11-28', '', 0, '[]', '', '', '', '', '', '', 1732752000000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2025-01-26-first', '', 'text', '其实我也在憧憬未来，即使眼下黑暗无光。', '<p>其实我也在憧憬未来，即使眼下黑暗无光。</p>', '', '2025-01-26', '', 0, '[]', '', '', '', '', '', '', 1737849600000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2025-02-01-first', '', 'text', '脑子里还是你挥之不去的记忆', '<p>脑子里还是你挥之不去的记忆</p>', '', '2025-02-01', '', 0, '[]', '', '', '', '', '', '', 1738368000000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2025-02-12-first', '', 'text', '不知道那张卡会不会被打开  
还是会被直接格式化了  
应该留给自己的', '<p>不知道那张卡会不会被打开  <br>还是会被直接格式化了  <br>应该留给自己的</p>', '', '2025-02-11', '', 0, '[]', '', '', '', '', '', '', 1739232000000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2025-02-25-first', '', 'text', '日落之后才是我们的时间', '<p>日落之后才是我们的时间</p>', '', '2025-02-25', '', 0, '[]', '', '', '', '', '', '', 1740441600000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2025-03-05-first', '', 'text', '又梦见你了,你从缅甸回来和我玩.', '<p>又梦见你了,你从缅甸回来和我玩.</p>', '', '2025-03-05', '', 0, '[]', '', '', '', '', '', '', 1741132800000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2025-03-11-first', '', 'text', '只是睡不着，顺便想起你。', '<p>只是睡不着，顺便想起你。</p>', '', '2025-03-11', '', 0, '[]', '', '', '', '', '', '', 1741651200000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2025-03-29-first', '', 'text', '谢谢你不远万里的来找我，那一定很难过吧。', '<p>谢谢你不远万里的来找我，那一定很难过吧。</p>', '', '2025-03-29', '', 0, '[]', '', '', '', '', '', '', 1743206400000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2025-03-30-first', '', 'text', '目前到此为止也挺好，省的以后再发生什么。', '<p>目前到此为止也挺好，省的以后再发生什么。</p>', '', '2025-03-30', '', 0, '[]', '', '', '', '', '', '', 1743292800000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2025-04-02-first', '', 'text', '因为被爱过所以知道你不爱我', '<p>因为被爱过所以知道你不爱我</p>', '', '2025-04-02', '', 0, '[]', '', '', '', '', '', '', 1743552000000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2026-04-04-first', '', 'text', '只是突然想试试，还能不能出现在你的列表里。', '<p>只是突然想试试，还能不能出现在你的列表里。</p>', '', '2026-04-04', '', 0, '[]', '', '', '', '', '', '', 1775260800000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2026-05-15-first', '', 'text', '不必纠结过往，时间会抚平一切', '<p>不必纠结过往，时间会抚平一切</p>', '', '2026-05-15', '', 0, '[]', '', '', '', '', '', '', 1778803200000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2026-05-22-first', '', 'text', '多年以后你会不会记得，有个女孩很努力的珍惜过你？', '<p>多年以后你会不会记得，有个女孩很努力的珍惜过你？</p>', '', '2026-07-02', '', 0, '[]', '', '', '', '', '', '', 1782950400000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2026-06-27', '', 'text', '愿我们都能成为更好的自己，也能遇见温柔的人。', '<p>愿我们都能成为更好的自己，也能遇见温柔的人。</p>', '', '2026-06-27', '', 0, '[]', '', '', '', '', '', '', 1782518400000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2026-06-28', '', 'text', '倘若我真的像电影里那样等了你三四年，一个能天天陪你三年的人
和一个等了你三四年的人 你选哪个.', '<p>倘若我真的像电影里那样等了你三四年，一个能天天陪你三年的人<br>和一个等了你三四年的人 你选哪个.</p>', '', '2026-06-28', '', 0, '[]', '', '', '', '', '', '', 1782604800000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2026-06-29', '咖啡馆时光', 'images', '', '', '上海 · 安福路', '2026-06-29', '', 0, '["https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=a%20cup%20of%20latte%20on%20wooden%20table%2C%20soft%20morning%20light%2C%20cozy%20cafe&image_size=square_hd","https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=open%20book%20with%20bookmark%2C%20warm%20tone%2C%20top%20view&image_size=square_hd","https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=croissant%20on%20ceramic%20plate%2C%20bakery%20aesthetic&image_size=square_hd"]', '', '', '', '', '', '', 1782691200000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2026-06-30', '海边日落', 'video', '海边的日落，波光粼粼，美不胜收。', '<p>海边的日落，波光粼粼，美不胜收。</p>', '青岛 · 八大关', '2026-06-30', '', 0, '[]', '', '', '', '', 'https://images.izhch.com/videos/17480866965452.mp4', '', 1782777600000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2026-07-01', '今日音乐', 'music', '', '', '杭州 · 西湖', '2026-07-01', '', 0, '[]', '起风了', '买辣椒也用券', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=album%20cover%20of%20wind%20blowing%20through%20wheat%20field%20at%20sunset%2C%20warm%20tone%2C%20cinematic&image_size=square_hd', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', '', '', 1782864000000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2026-07-03-first', '', 'text', '明明说着不在乎，

却会留意对方更了没，最近怎么了

明明说着不想念，

却会在无聊的时候不期然的想起以往的画面', '<p>明明说着不在乎，</p>
<p>却会留意对方更了没，最近怎么了</p>
<p>明明说着不想念，</p>
<p>却会在无聊的时候不期然的想起以往的画面</p>', '', '2026-07-03', '', 0, '[]', '', '', '', '', '', '', 1783036800000, 0);
INSERT INTO moments (id, title, type, content, content_html, location, created_at, password_hash, collapse, images, music_title, music_artist, music_cover, music_src, video_src, video_duration, sort_order, is_deleted) VALUES ('2026-07-07-password-demo', '', 'text', '这是一篇密码保护的测试文章。

密码是：**1234**

只有输入正确的密码才能看到这篇文章的内容。

这个功能是前端实现的，属于"防君子不防小人"的社交功能，不是真正的安全措施。', '<p>这是一篇密码保护的测试文章。</p>
<p>密码是：<strong>1234</strong></p>
<p>只有输入正确的密码才能看到这篇文章的内容。</p>
<p>这个功能是前端实现的，属于"防君子不防小人"的社交功能，不是真正的安全措施。</p>', '测试地点 · 密码示例', '2026-07-07', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 0, '[]', '', '', '', '', '', '', 1783382400000, 0);

-- 迁移完成